#ifndef __defines_HH__
#define __defines_HH__

#define WIDTH 1365
#define HEIGHT 1024
#define BACK_IMG_PATH "./Assets/background.png"
#define GAME_TITLE "FieldRunners"
#define HEART_X 1000
#define HEART_Y 10
#define HEART_PATH "./heart.png"
#define TTF_HEART_PATH "./money.ttf"
#define MONEY_X 800
#define MONEY_Y 10
#define MONEY_PATH "./money.png"
#define TTF_MONEY_PATH "./money.TTF"
#define FIRST_MONEY 200
#define FIRST_HEART 20
#define SPACE ' '
#define POS_X_0_0 150
#define POS_Y_0_0 205
#define NUM_OF_ROW 10
#define NUM_OF_COL 18
#define SIZE_OF_SQUARE 60
#define CLICK_DELAY 200
#define NOT_END -1
#define LOSE_END 0
#define WIN_END 1
#define WIN_PIC_PATH "./you_win.jpg"
#define LOSE_PIC_PATH "./you_lose.jpg"
#define DELAY_OF_WAVES 3000
#define GAME_DELAY 10
#define PATH_OF_PATH_PIC "./path4.png"
#define KILL_DELAY 1500
#define RANGE_OF_TOWERS 150
#define NOTHING '0'
#define END_UP_TIME 2500
#define GATLING "Gatling"
#define TESLA "Tesla"
#define MISSILE "Missile"
#define GLUE "Glue"
#define RANGE_OF_MISSILE_SHOT 50
#define RANGE_OF_GLUE_SHOT 30
#define DELAY_OF_NEW_ENEMIES 500
#define NUM_OF_ENEMIES 4
#define G 'g'
#define M 'm'
#define T 't'
#define L 'l'
#define U 'u'
#define SHOT_DELAY 100
#define TIME_OF_CHANGE_FRAME 100
#define MAX_FRAME_FOR_RUN 6
#define MAX_FRAME_FOR_DIE 5
#define TEN 10
#define MAX_LEVEL 2
#define MAX_X_OF_BOARD 1261
#define MIN_X_OF_BOARD 77
#define MAX_Y_OF_BOARD 834
#define MIN_Y_OF_BOARD 175
#define NEW_TOWER 0
#define MOUSE_IN 1
#define ENEMY_IN 2
#define LEVEL_1 0
#define LEVEL_2 1
#define LEVEL_3 2
#define NINETY 90
#define INDEX_OF_ATTACK_2 2
#define INDEX_OF_ATTACK_3 3
#define RUNNING_RIGHT 0
#define RUNNING_DOWN 1
#define RUNNING_LEFT 2
#define RUNNING_UP 3
#define DEATH 4 
#define KILL_CHANGE_FRAME_TIME 150
#define MAX_TRY 5
#define MAX_BACK_FRAME 13
#define REDUCE_BRIGHTNESS_DELAY 150
#define PATH_DELAY 175
#define PATH_MAX_FRAME 5
#define PNG ".png"
#define JPG ".jpg"
#define MISSILE_COST 70
#define GLUE_COST 60
#define TESLA_COST 120
#define GATLING_COST 55
#define MIS_ICON_X 739
#define MIS_ICON_Y 917
#define MIS_ICON_W 109
#define MIS_ICON_H 108
#define GLUE_ICON_X 846
#define GLUE_ICON_Y 930
#define GLUE_ICON_W 101
#define GLUE_ICON_H 97
#define TESLA_ICON_X 1152
#define TESLA_ICON_Y 926
#define TESLA_ICON_W 102
#define TESLA_ICON_H 96
#define GAT_ICON_X 1045
#define GAT_ICON_Y 927
#define GAT_ICON_W 101
#define GAT_ICON_H 98
#define MIS_ICON "./mis_icon"
#define GLUE_ICON "./glue_icon"
#define TESLA_ICON "./tesla_icon"
#define GAT_ICON "./cat_icon"
#define END_WIN "end00.png"
#define END_LOSE "end11.png"
#define X "x"
#define Y "y"
#define COLLISION_DELAY 200
#define MAX_COLLISION_FRAME 5
#define NUMBER_OF_LEVELS 3
#define DELTA_Y 4

#endif